server:
  port: 7788

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: xttblog-feign-hystrix

feign:
  hystrix:
    enabled: true
